### ISSUE TITLE
minor issues for first timers

### ISSUE THREAD

**Issue by RudolphRiedel** [sipeed/Longan_GD32VF_examples#1]
I had to use "framework = gd32vf103-sdk" in platformio.ini to make it build.
Also, adding "upload_protocol = dfu" was usefull.

When the boards are delivered there is no clue whatsoever what software is installed.
The rgb LEDs blink and the LCD is emulating a big white LED.
This is of course only because the files are not supplied on µSD-card.
A little hint on the LCD could be helpfull, like "no card found".
The application is way under 20k, so adding an image that is linked to the binary should be no issue at all.

**Comment by greedyhao** [comment]
The problem has been solved.

**Comment by RudolphRiedel** [comment]
I just tried it and it just builds now and displays "no card found!" in five lines with different colors.
Excellent, thank you!
